/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param id ユーザーUUID
 * @param role ユーザーの役割
 */
@Serializable

data class AddUserGroupMemberRequest(

    /* ユーザーUUID */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* ユーザーの役割 */
    @SerialName(value = "role") @Required val role: kotlin.String

) {


}

