/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * BOTイベントログ
 *
 * @param botId BOT UUID
 * @param requestId リクエストUUID
 * @param event イベントタイプ
 * @param code ステータスコード
 * @param datetime イベント日時
 * @param result
 */
@Serializable

data class BotEventLog(

    /* BOT UUID */
    @SerialName(value = "botId") @Required val botId: kotlin.String,

    /* リクエストUUID */
    @SerialName(value = "requestId") @Required val requestId: kotlin.String,

    /* イベントタイプ */
    @SerialName(value = "event") @Required val event: kotlin.String,

    /* ステータスコード */
    @SerialName(value = "code") @Required val code: kotlin.Int,

    /* イベント日時 */
    @SerialName(value = "datetime") @Required val datetime: kotlinx.datetime.Instant,

    @SerialName(value = "result") val result: BotEventResult? = null

) {


}

