/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * イベント配送結果
 *
 * Values: OK,NG,NetworkError,Dropped
 */
@Serializable
enum class BotEventResult(val value: kotlin.String) {

    @SerialName(value = "ok")
    OK("ok"),

    @SerialName(value = "ng")
    NG("ng"),

    @SerialName(value = "ne")
    NetworkError("ne"),

    @SerialName(value = "dp")
    Dropped("dp");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is BotEventResult) "$data" else null

        /**
         * Returns a valid [BotEventResult] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): BotEventResult? = data?.let {
            val normalizedData = "$it".lowercase()
            values().firstOrNull { value ->
                it == value || normalizedData == "$value".lowercase()
            }
        }
    }
}

