/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * BOT状態 0: 停止 1: 有効 2: 一時停止
 *
 * Values: deactivated,active,suspended
 */
@Serializable
enum class BotState(val value: kotlin.Int) {

    @SerialName(value = "0")
    deactivated(0),

    @SerialName(value = "1")
    active(1),

    @SerialName(value = "2")
    suspended(2);

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value.toString()

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is BotState) "$data" else null

        /**
         * Returns a valid [BotState] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): BotState? = data?.let {
            val normalizedData = "$it".lowercase()
            values().firstOrNull { value ->
                it == value || normalizedData == "$value".lowercase()
            }
        }
    }
}

