/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * イベント内容
 *
 * @param userId 作成者UUID
 * @param before 変更前親チャンネルUUID
 * @param after 変更後親チャンネルUUID
 * @param on オンにされたユーザーのUUID配列
 * @param off オフにされたユーザーのUUID配列
 * @param messageId メッセージUUID
 * @param visibility 変更後可視状態
 * @param force 変更後強制通知状態
 * @param channelId チャンネルUUID
 */
@Serializable

data class ChannelEventDetail(

    /* 作成者UUID */
    @SerialName(value = "userId") @Required val userId: kotlin.String,

    /* 変更前親チャンネルUUID */
    @SerialName(value = "before") @Required val before: kotlin.String,

    /* 変更後親チャンネルUUID */
    @SerialName(value = "after") @Required val after: kotlin.String,

    /* オンにされたユーザーのUUID配列 */
    @SerialName(value = "on") @Required val on: kotlin.collections.List<kotlin.String>,

    /* オフにされたユーザーのUUID配列 */
    @SerialName(value = "off") @Required val off: kotlin.collections.List<kotlin.String>,

    /* メッセージUUID */
    @SerialName(value = "messageId") @Required val messageId: kotlin.String,

    /* 変更後可視状態 */
    @SerialName(value = "visibility") @Required val visibility: kotlin.Boolean,

    /* 変更後強制通知状態 */
    @SerialName(value = "force") @Required val force: kotlin.Boolean,

    /* チャンネルUUID */
    @SerialName(value = "channelId") @Required val channelId: kotlin.String

) {


}

