/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * チャンネル上の特定ユーザー統計情報
 *
 * @param id ユーザーID
 * @param messageCount メッセージ数
 */
@Serializable

data class ChannelStatsUser(

    /* ユーザーID */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* メッセージ数 */
    @SerialName(value = "messageCount") @Required val messageCount: kotlin.Long

) {


}

