/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * チャンネル上の特定スタンプ統計情報
 *
 * @param id スタンプID
 * @param count スタンプ数(同一メッセージ上のものは複数カウントしない)
 * @param total スタンプ数(同一メッセージ上のものも複数カウントする)
 */
@Serializable

data class ChannelStatsStamp(

    /* スタンプID */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* スタンプ数(同一メッセージ上のものは複数カウントしない) */
    @SerialName(value = "count") @Required val count: kotlin.Long,

    /* スタンプ数(同一メッセージ上のものも複数カウントする) */
    @SerialName(value = "total") @Required val total: kotlin.Long

) {


}

