/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * チャンネル
 *
 * @param id チャンネルUUID
 * @param parentId 親チャンネルUUID
 * @param archived チャンネルがアーカイブされているかどうか
 * @param force 強制通知チャンネルかどうか
 * @param topic チャンネルトピック
 * @param name チャンネル名
 * @param children 子チャンネルのUUID配列
 */
@Serializable

data class Channel(

    /* チャンネルUUID */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* 親チャンネルUUID */
    @SerialName(value = "parentId") @Required val parentId: kotlin.String?,

    /* チャンネルがアーカイブされているかどうか */
    @SerialName(value = "archived") @Required val archived: kotlin.Boolean,

    /* 強制通知チャンネルかどうか */
    @SerialName(value = "force") @Required val force: kotlin.Boolean,

    /* チャンネルトピック */
    @SerialName(value = "topic") @Required val topic: kotlin.String,

    /* チャンネル名 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* 子チャンネルのUUID配列 */
    @SerialName(value = "children") @Required val children: kotlin.collections.List<kotlin.String>

) {


}

