/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * メッセージ引用通知の設定情報
 *
 * @param notifyCitation
 */
@Serializable

data class GetNotifyCitation(

    @SerialName(value = "notifyCitation") @Required val notifyCitation: kotlin.Boolean

) {


}

