/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * ログインセッション情報
 *
 * @param id セッションUUID
 * @param issuedAt 発行日時
 */
@Serializable

data class LoginSession(

    /* セッションUUID */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* 発行日時 */
    @SerialName(value = "issuedAt") @Required val issuedAt: kotlinx.datetime.Instant

) {


}

