/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * メッセージ検索結果
 *
 * @param totalHits 検索にヒットしたメッセージ件数
 * @param hits 検索にヒットしたメッセージの配列
 */
@Serializable

data class MessageSearchResult(

    /* 検索にヒットしたメッセージ件数 */
    @SerialName(value = "totalHits") @Required val totalHits: kotlin.Long,

    /* 検索にヒットしたメッセージの配列 */
    @SerialName(value = "hits") @Required val hits: kotlin.collections.List<Message>

) {


}

