/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * メッセージクリップ
 *
 * @param folderId クリップされているフォルダのID
 * @param clippedAt クリップされた日時
 */
@Serializable

data class MessageClip(

    /* クリップされているフォルダのID */
    @SerialName(value = "folderId") @Required val folderId: kotlin.String,

    /* クリップされた日時 */
    @SerialName(value = "clippedAt") @Required val clippedAt: kotlinx.datetime.Instant

) {


}

