/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 自身のチャンネル閲覧状態
 *
 * @param key WSセッションの識別子
 * @param channelId チャンネルUUID
 * @param state
 */
@Serializable

data class MyChannelViewState(

    /* WSセッションの識別子 */
    @SerialName(value = "key") @Required val key: kotlin.String,

    /* チャンネルUUID */
    @SerialName(value = "channelId") @Required val channelId: kotlin.String,

    @SerialName(value = "state") @Required val state: ChannelViewState

) {


}

