/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 自分のユーザー詳細情報
 *
 * @param id ユーザーUUID
 * @param bio 自己紹介(biography)
 * @param groups 所属グループのUUIDの配列
 * @param tags タグリスト
 * @param updatedAt 更新日時
 * @param lastOnline 最終オンライン日時
 * @param twitterId Twitter ID
 * @param name ユーザー名
 * @param displayName ユーザー表示名
 * @param iconFileId アイコンファイルUUID
 * @param bot BOTかどうか
 * @param state
 * @param permissions 所有している権限の配列
 * @param homeChannel ホームチャンネル
 */
@Serializable

data class MyUserDetail(

    /* ユーザーUUID */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* 自己紹介(biography) */
    @SerialName(value = "bio") @Required val bio: kotlin.String,

    /* 所属グループのUUIDの配列 */
    @SerialName(value = "groups") @Required val groups: kotlin.collections.List<kotlin.String>,

    /* タグリスト */
    @SerialName(value = "tags") @Required val tags: kotlin.collections.List<UserTag>,

    /* 更新日時 */
    @SerialName(value = "updatedAt") @Required val updatedAt: kotlinx.datetime.Instant,

    /* 最終オンライン日時 */
    @SerialName(value = "lastOnline") @Required val lastOnline: kotlinx.datetime.Instant?,

    /* Twitter ID */
    @SerialName(value = "twitterId") @Required val twitterId: kotlin.String,

    /* ユーザー名 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* ユーザー表示名 */
    @SerialName(value = "displayName") @Required val displayName: kotlin.String,

    /* アイコンファイルUUID */
    @SerialName(value = "iconFileId") @Required val iconFileId: kotlin.String,

    /* BOTかどうか */
    @SerialName(value = "bot") @Required val bot: kotlin.Boolean,

    @SerialName(value = "state") @Required val state: UserAccountState,

    /* 所有している権限の配列 */
    @SerialName(value = "permissions") @Required val permissions: kotlin.collections.List<UserPermission>,

    /* ホームチャンネル */
    @SerialName(value = "homeChannel") @Required val homeChannel: kotlin.String?

) {


}

