/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * OAuth2クライアント詳細情報
 *
 * @param id クライアントUUID
 * @param developerId クライアント開発者UUID
 * @param description 説明
 * @param name クライアント名
 * @param scopes 要求スコープの配列
 * @param callbackUrl コールバックURL
 * @param secret クライアントシークレット
 * @param confidential confidential client なら true, public client なら false
 */
@Serializable

data class OAuth2ClientDetail(

    /* クライアントUUID */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* クライアント開発者UUID */
    @SerialName(value = "developerId") @Required val developerId: kotlin.String,

    /* 説明 */
    @SerialName(value = "description") @Required val description: kotlin.String,

    /* クライアント名 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* 要求スコープの配列 */
    @SerialName(value = "scopes") @Required val scopes: kotlin.collections.List<OAuth2Scope>,

    /* コールバックURL */
    @SerialName(value = "callbackUrl") @Required val callbackUrl: kotlin.String,

    /* クライアントシークレット */
    @SerialName(value = "secret") @Required val secret: kotlin.String,

    /* confidential client なら true, public client なら false */
    @SerialName(value = "confidential") @Required val confidential: kotlin.Boolean

) {


}

