/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param accessToken
 * @param tokenType
 * @param expiresIn
 * @param refreshToken
 * @param scope
 * @param idToken
 */
@Serializable

data class OAuth2Token(

    @SerialName(value = "access_token") @Required val accessToken: kotlin.String,

    @SerialName(value = "token_type") @Required val tokenType: kotlin.String,

    @SerialName(value = "expires_in") val expiresIn: kotlin.Int? = null,

    @SerialName(value = "refresh_token") val refreshToken: kotlin.String? = null,

    @SerialName(value = "scope") val scope: kotlin.String? = null,

    @SerialName(value = "id_token") val idToken: kotlin.String? = null

) {


}

