/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 自分のユーザー詳細情報
 *
 * @param sub ユーザーUUID
 * @param name ユーザー名
 * @param preferredUsername ユーザー名
 * @param picture アイコン画像URL
 * @param updatedAt 更新日時
 * @param traq
 */
@Serializable

data class OIDCUserInfo(

    /* ユーザーUUID */
    @SerialName(value = "sub") @Required val sub: kotlin.String,

    /* ユーザー名 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* ユーザー名 */
    @SerialName(value = "preferred_username") @Required val preferredUsername: kotlin.String,

    /* アイコン画像URL */
    @SerialName(value = "picture") @Required val picture: kotlin.String,

    /* 更新日時 */
    @SerialName(value = "updated_at") val updatedAt: kotlin.Long? = null,

    @SerialName(value = "traq") val traq: OIDCTraqUserInfo? = null

) {


}

