/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * スタンプパレット情報変更リクエスト
 *
 * @param name パレット名
 * @param description 説明
 * @param stamps パレット内のスタンプUUIDの配列
 */
@Serializable

data class PatchStampPaletteRequest(

    /* パレット名 */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* 説明 */
    @SerialName(value = "description") val description: kotlin.String? = null,

    /* パレット内のスタンプUUIDの配列 */
    @SerialName(value = "stamps") val stamps: kotlin.collections.Set<kotlin.String>? = null

) {


}

