/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * BOT情報変更リクエスト
 *
 * @param displayName BOTユーザー表示名
 * @param description BOTの説明
 * @param privileged 特権
 * @param mode
 * @param endpoint BOTサーバーエンドポイント
 * @param developerId 移譲先の開発者UUID
 * @param subscribeEvents 購読するイベント
 * @param bio 自己紹介(biography)
 */
@Serializable

data class PatchBotRequest(

    /* BOTユーザー表示名 */
    @SerialName(value = "displayName") val displayName: kotlin.String? = null,

    /* BOTの説明 */
    @SerialName(value = "description") val description: kotlin.String? = null,

    /* 特権 */
    @SerialName(value = "privileged") val privileged: kotlin.Boolean? = null,

    @SerialName(value = "mode") val mode: BotMode? = null,

    /* BOTサーバーエンドポイント */
    @SerialName(value = "endpoint") val endpoint: kotlin.String? = null,

    /* 移譲先の開発者UUID */
    @SerialName(value = "developerId") val developerId: kotlin.String? = null,

    /* 購読するイベント */
    @SerialName(value = "subscribeEvents") val subscribeEvents: kotlin.collections.List<kotlin.String>? = null,

    /* 自己紹介(biography) */
    @SerialName(value = "bio") val bio: kotlin.String? = null

) {


}

