/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * チャンネル購読者編集リクエスト
 *
 * @param on 通知をオンにするユーザーのUUID配列
 * @param off 通知をオフにするユーザーのUUID配列
 */
@Serializable

data class PatchChannelSubscribersRequest(

    /* 通知をオンにするユーザーのUUID配列 */
    @SerialName(value = "on") val on: kotlin.collections.List<kotlin.String>? = null,

    /* 通知をオフにするユーザーのUUID配列 */
    @SerialName(value = "off") val off: kotlin.collections.List<kotlin.String>? = null

) {


}

