/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * POST /users/me/ex-accounts/link 用リクエストボディ
 *
 * @param providerName 外部サービス名
 */
@Serializable

data class PostLinkExternalAccount(

    /* 外部サービス名 */
    @SerialName(value = "providerName") @Required val providerName: kotlin.String

) {


}

