/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * クリップフォルダ作成リクエスト
 *
 * @param name フォルダ名
 * @param description 説明
 */
@Serializable

data class PostClipFolderRequest(

    /* フォルダ名 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* 説明 */
    @SerialName(value = "description") @Required val description: kotlin.String

) {


}

