/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * OAuth2クライアント作成リクエスト
 *
 * @param name クライアント名
 * @param callbackUrl コールバックURL
 * @param scopes 要求スコープの配列
 * @param description 説明
 * @param confidential confidential client なら true, public cleint なら false
 */
@Serializable

data class PostClientRequest(

    /* クライアント名 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* コールバックURL */
    @SerialName(value = "callbackUrl") @Required val callbackUrl: kotlin.String,

    /* 要求スコープの配列 */
    @SerialName(value = "scopes") @Required val scopes: kotlin.collections.List<OAuth2Scope>,

    /* 説明 */
    @SerialName(value = "description") @Required val description: kotlin.String,

    /* confidential client なら true, public cleint なら false */
    @SerialName(value = "confidential") val confidential: kotlin.Boolean? = false

) {


}

