/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * グループ管理者追加リクエスト
 *
 * @param id 追加するユーザーのUUID
 */
@Serializable

data class PostUserGroupAdminRequest(

    /* 追加するユーザーのUUID */
    @SerialName(value = "id") @Required val id: kotlin.String

) {


}

