/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * ログインリクエスト
 *
 * @param name ユーザー名
 * @param password パスワード
 */
@Serializable

data class PostLoginRequest(

    /* ユーザー名 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* パスワード */
    @SerialName(value = "password") @Required val password: kotlin.String

) {


}

