/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * パスワード変更リクエスト
 *
 * @param password 現在のパスワード
 * @param newPassword 新しいパスワード
 */
@Serializable

data class PutMyPasswordRequest(

    /* 現在のパスワード */
    @SerialName(value = "password") @Required val password: kotlin.String,

    /* 新しいパスワード */
    @SerialName(value = "newPassword") @Required val newPassword: kotlin.String

) {


}

