/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param participantId 対象参加者ID
 * @param status success もしくは error
 * @param errorMessage エラーがある場合の詳細
 */
@Serializable

data class QallParticipantResponseResultsInner(

    /* 対象参加者ID */
    @SerialName(value = "participantId") val participantId: kotlin.String? = null,

    /* success もしくは error */
    @SerialName(value = "status") val status: kotlin.String? = null,

    /* エラーがある場合の詳細 */
    @SerialName(value = "errorMessage") val errorMessage: kotlin.String? = null

) {


}

