/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Qallのサウンドボードアイテムが削除された
 *
 * @param soundId 削除されたサウンドボードアイテムのId
 */
@Serializable

data class QallSoundboardItemDeletedEvent(

    /* 削除されたサウンドボードアイテムのId */
    @SerialName(value = "soundId") @Required val soundId: kotlin.String

) {


}

