/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Qallのサウンドボードアイテムが作成された
 *
 * @param soundId 作成されたサウンドボードアイテムのId
 * @param name 作成されたサウンドボードアイテムの名前
 * @param creatorId 作成者のId
 */
@Serializable

data class QallSoundboardItemCreatedEvent(

    /* 作成されたサウンドボードアイテムのId */
    @SerialName(value = "soundId") @Required val soundId: kotlin.String,

    /* 作成されたサウンドボードアイテムの名前 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* 作成者のId */
    @SerialName(value = "creatorId") @Required val creatorId: kotlin.String

) {


}

