/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param state 状態
 * @param sessionId セッションID
 */
@Serializable

data class Session(

    /* 状態 */
    @SerialName(value = "state") @Required val state: kotlin.String,

    /* セッションID */
    @SerialName(value = "sessionId") @Required val sessionId: kotlin.String

) {


}

