/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * スタンプ履歴の1項目
 *
 * @param stampId スタンプUUID
 * @param datetime 使用日時
 */
@Serializable

data class StampHistoryEntry(

    /* スタンプUUID */
    @SerialName(value = "stampId") @Required val stampId: kotlin.String,

    /* 使用日時 */
    @SerialName(value = "datetime") @Required val datetime: kotlinx.datetime.Instant

) {


}

