/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * スタンプパレット情報
 *
 * @param id スタンプパレットUUID
 * @param name パレット名
 * @param stamps パレット内のスタンプのUUID配列
 * @param creatorId 作成者UUID
 * @param createdAt パレット作成日時
 * @param updatedAt パレット更新日時
 * @param description パレット説明
 */
@Serializable

data class StampPalette(

    /* スタンプパレットUUID */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* パレット名 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* パレット内のスタンプのUUID配列 */
    @SerialName(value = "stamps") @Required val stamps: kotlin.collections.List<kotlin.String>,

    /* 作成者UUID */
    @SerialName(value = "creatorId") @Required val creatorId: kotlin.String,

    /* パレット作成日時 */
    @SerialName(value = "createdAt") @Required val createdAt: kotlinx.datetime.Instant,

    /* パレット更新日時 */
    @SerialName(value = "updatedAt") @Required val updatedAt: kotlinx.datetime.Instant,

    /* パレット説明 */
    @SerialName(value = "description") @Required val description: kotlin.String

) {


}

