/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * タグ情報
 *
 * @param id タグUUID
 * @param tag タグ文字列
 * @param users タグがつけられているユーザーのUUID配列
 */
@Serializable

data class Tag(

    /* タグUUID */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* タグ文字列 */
    @SerialName(value = "tag") @Required val tag: kotlin.String,

    /* タグがつけられているユーザーのUUID配列 */
    @SerialName(value = "users") @Required val users: kotlin.collections.List<kotlin.String>

) {


}

