/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * ユーザー統計情報
 *
 * @param totalMessageCount ユーザーの総投稿メッセージ数(削除されたものも含む)
 * @param stamps ユーザーのスタンプ統計情報
 * @param datetime 統計情報日時
 */
@Serializable

data class UserStats(

    /* ユーザーの総投稿メッセージ数(削除されたものも含む) */
    @SerialName(value = "totalMessageCount") @Required val totalMessageCount: kotlin.Long,

    /* ユーザーのスタンプ統計情報 */
    @SerialName(value = "stamps") @Required val stamps: kotlin.collections.List<UserStatsStamp>,

    /* 統計情報日時 */
    @SerialName(value = "datetime") @Required val datetime: kotlinx.datetime.Instant

) {


}

