/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * ユーザー権限
 *
 * Values: GetWebhook,CreateWebhook,EditWebhook,DeleteWebhook,AccessOthersWebhook,GetBot,CreateBot,EditBot,DeleteBot,AccessOthersBot,BotActionJoinChannel,BotActionLeaveChannel,CreateChannel,GetChannel,EditChannel,DeleteChannel,ChangeParentChannel,EditChannelTopic,GetChannelStar,EditChannelStar,GetMyTokens,RevokeMyToken,GetClients,CreateClient,EditMyClient,DeleteMyClient,ManageOthersClient,UploadFile,DownloadFile,DeleteFile,GetMessage,PostMessage,EditMessage,DeleteMessage,ReportMessage,GetMessageReports,CreateMessagePin,DeleteMessagePin,GetChannelSubscription,EditChannelSubscription,ConnectNotificationStream,RegisterFCMDevice,GetStamp,CreateStamp,EditStamp,EditStampCreatedByOthers,DeleteStamp,DeleteMyStamp,AddMessageStamp,RemoveMessageStamp,GetMyStampHistory,GetStampPalette,CreateStampPalette,EditStampPalette,DeleteStampPalette,GetUser,RegisterUser,GetMe,GetOIDCUserInfo,EditMe,ChangeMyIcon,ChangeMyPassword,EditOtherUsers,GetUserQRCode,GetUserTag,EditUserTag,GetUserGroup,CreateUserGroup,CreateSpecialUserGroup,EditUserGroup,DeleteUserGroup,AllUserGroupsAdmin,WebRTC,GetMySessions,DeleteMySessions,GetMyExternalAccount,EditMyExternalAccount,GetUnread,DeleteUnread,GetClipFolder,CreateClipFolder,EditClipFolder,DeleteClipFolder
 */
@Serializable
enum class UserPermission(val value: kotlin.String) {

    @SerialName(value = "get_webhook")
    GetWebhook("get_webhook"),

    @SerialName(value = "create_webhook")
    CreateWebhook("create_webhook"),

    @SerialName(value = "edit_webhook")
    EditWebhook("edit_webhook"),

    @SerialName(value = "delete_webhook")
    DeleteWebhook("delete_webhook"),

    @SerialName(value = "access_others_webhook")
    AccessOthersWebhook("access_others_webhook"),

    @SerialName(value = "get_bot")
    GetBot("get_bot"),

    @SerialName(value = "create_bot")
    CreateBot("create_bot"),

    @SerialName(value = "edit_bot")
    EditBot("edit_bot"),

    @SerialName(value = "delete_bot")
    DeleteBot("delete_bot"),

    @SerialName(value = "access_others_bot")
    AccessOthersBot("access_others_bot"),

    @SerialName(value = "bot_action_join_channel")
    BotActionJoinChannel("bot_action_join_channel"),

    @SerialName(value = "bot_action_leave_channel")
    BotActionLeaveChannel("bot_action_leave_channel"),

    @SerialName(value = "create_channel")
    CreateChannel("create_channel"),

    @SerialName(value = "get_channel")
    GetChannel("get_channel"),

    @SerialName(value = "edit_channel")
    EditChannel("edit_channel"),

    @SerialName(value = "delete_channel")
    DeleteChannel("delete_channel"),

    @SerialName(value = "change_parent_channel")
    ChangeParentChannel("change_parent_channel"),

    @SerialName(value = "edit_channel_topic")
    EditChannelTopic("edit_channel_topic"),

    @SerialName(value = "get_channel_star")
    GetChannelStar("get_channel_star"),

    @SerialName(value = "edit_channel_star")
    EditChannelStar("edit_channel_star"),

    @SerialName(value = "get_my_tokens")
    GetMyTokens("get_my_tokens"),

    @SerialName(value = "revoke_my_token")
    RevokeMyToken("revoke_my_token"),

    @SerialName(value = "get_clients")
    GetClients("get_clients"),

    @SerialName(value = "create_client")
    CreateClient("create_client"),

    @SerialName(value = "edit_my_client")
    EditMyClient("edit_my_client"),

    @SerialName(value = "delete_my_client")
    DeleteMyClient("delete_my_client"),

    @SerialName(value = "manage_others_client")
    ManageOthersClient("manage_others_client"),

    @SerialName(value = "upload_file")
    UploadFile("upload_file"),

    @SerialName(value = "download_file")
    DownloadFile("download_file"),

    @SerialName(value = "delete_file")
    DeleteFile("delete_file"),

    @SerialName(value = "get_message")
    GetMessage("get_message"),

    @SerialName(value = "post_message")
    PostMessage("post_message"),

    @SerialName(value = "edit_message")
    EditMessage("edit_message"),

    @SerialName(value = "delete_message")
    DeleteMessage("delete_message"),

    @SerialName(value = "report_message")
    ReportMessage("report_message"),

    @SerialName(value = "get_message_reports")
    GetMessageReports("get_message_reports"),

    @SerialName(value = "create_message_pin")
    CreateMessagePin("create_message_pin"),

    @SerialName(value = "delete_message_pin")
    DeleteMessagePin("delete_message_pin"),

    @SerialName(value = "get_channel_subscription")
    GetChannelSubscription("get_channel_subscription"),

    @SerialName(value = "edit_channel_subscription")
    EditChannelSubscription("edit_channel_subscription"),

    @SerialName(value = "connect_notification_stream")
    ConnectNotificationStream("connect_notification_stream"),

    @SerialName(value = "register_fcm_device")
    RegisterFCMDevice("register_fcm_device"),

    @SerialName(value = "get_stamp")
    GetStamp("get_stamp"),

    @SerialName(value = "create_stamp")
    CreateStamp("create_stamp"),

    @SerialName(value = "edit_stamp")
    EditStamp("edit_stamp"),

    @SerialName(value = "edit_stamp_created_by_others")
    EditStampCreatedByOthers("edit_stamp_created_by_others"),

    @SerialName(value = "delete_stamp")
    DeleteStamp("delete_stamp"),

    @SerialName(value = "delete_my_stamp")
    DeleteMyStamp("delete_my_stamp"),

    @SerialName(value = "add_message_stamp")
    AddMessageStamp("add_message_stamp"),

    @SerialName(value = "remove_message_stamp")
    RemoveMessageStamp("remove_message_stamp"),

    @SerialName(value = "get_my_stamp_history")
    GetMyStampHistory("get_my_stamp_history"),

    @SerialName(value = "get_stamp_palette")
    GetStampPalette("get_stamp_palette"),

    @SerialName(value = "create_stamp_palette")
    CreateStampPalette("create_stamp_palette"),

    @SerialName(value = "edit_stamp_palette")
    EditStampPalette("edit_stamp_palette"),

    @SerialName(value = "delete_stamp_palette")
    DeleteStampPalette("delete_stamp_palette"),

    @SerialName(value = "get_user")
    GetUser("get_user"),

    @SerialName(value = "register_user")
    RegisterUser("register_user"),

    @SerialName(value = "get_me")
    GetMe("get_me"),

    @SerialName(value = "get_oidc_userinfo")
    GetOIDCUserInfo("get_oidc_userinfo"),

    @SerialName(value = "edit_me")
    EditMe("edit_me"),

    @SerialName(value = "change_my_icon")
    ChangeMyIcon("change_my_icon"),

    @SerialName(value = "change_my_password")
    ChangeMyPassword("change_my_password"),

    @SerialName(value = "edit_other_users")
    EditOtherUsers("edit_other_users"),

    @SerialName(value = "get_user_qr_code")
    GetUserQRCode("get_user_qr_code"),

    @SerialName(value = "get_user_tag")
    GetUserTag("get_user_tag"),

    @SerialName(value = "edit_user_tag")
    EditUserTag("edit_user_tag"),

    @SerialName(value = "get_user_group")
    GetUserGroup("get_user_group"),

    @SerialName(value = "create_user_group")
    CreateUserGroup("create_user_group"),

    @SerialName(value = "create_special_user_group")
    CreateSpecialUserGroup("create_special_user_group"),

    @SerialName(value = "edit_user_group")
    EditUserGroup("edit_user_group"),

    @SerialName(value = "delete_user_group")
    DeleteUserGroup("delete_user_group"),

    @SerialName(value = "edit_others_user_group")
    AllUserGroupsAdmin("edit_others_user_group"),

    @SerialName(value = "web_rtc")
    WebRTC("web_rtc"),

    @SerialName(value = "get_my_sessions")
    GetMySessions("get_my_sessions"),

    @SerialName(value = "delete_my_sessions")
    DeleteMySessions("delete_my_sessions"),

    @SerialName(value = "get_my_external_account")
    GetMyExternalAccount("get_my_external_account"),

    @SerialName(value = "edit_my_external_account")
    EditMyExternalAccount("edit_my_external_account"),

    @SerialName(value = "get_unread")
    GetUnread("get_unread"),

    @SerialName(value = "delete_unread")
    DeleteUnread("delete_unread"),

    @SerialName(value = "get_clip_folder")
    GetClipFolder("get_clip_folder"),

    @SerialName(value = "create_clip_folder")
    CreateClipFolder("create_clip_folder"),

    @SerialName(value = "edit_clip_folder")
    EditClipFolder("edit_clip_folder"),

    @SerialName(value = "delete_clip_folder")
    DeleteClipFolder("delete_clip_folder");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is UserPermission) "$data" else null

        /**
         * Returns a valid [UserPermission] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): UserPermission? = data?.let {
            val normalizedData = "$it".lowercase()
            values().firstOrNull { value ->
                it == value || normalizedData == "$value".lowercase()
            }
        }
    }
}

