/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * ユーザーのチャンネル購読状態
 *
 * @param channelId チャンネルUUID
 * @param level
 */
@Serializable

data class UserSubscribeState(

    /* チャンネルUUID */
    @SerialName(value = "channelId") @Required val channelId: kotlin.String,

    @SerialName(value = "level") @Required val level: ChannelSubscribeLevel

) {


}

