/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * ユーザータグ
 *
 * @param tagId タグUUID
 * @param tag タグ文字列
 * @param isLocked タグがロックされているか
 * @param createdAt タグ付与日時
 * @param updatedAt タグ更新日時
 */
@Serializable

data class UserTag(

    /* タグUUID */
    @SerialName(value = "tagId") @Required val tagId: kotlin.String,

    /* タグ文字列 */
    @SerialName(value = "tag") @Required val tag: kotlin.String,

    /* タグがロックされているか */
    @SerialName(value = "isLocked") @Required val isLocked: kotlin.Boolean,

    /* タグ付与日時 */
    @SerialName(value = "createdAt") @Required val createdAt: kotlinx.datetime.Instant,

    /* タグ更新日時 */
    @SerialName(value = "updatedAt") @Required val updatedAt: kotlinx.datetime.Instant

) {


}

