/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * バージョン・サーバーフラグ情報
 *
 * @param revision traQ(サーバー)リビジョン
 * @param version traQ(サーバー)バージョン
 * @param flags
 */
@Serializable

data class Version(

    /* traQ(サーバー)リビジョン */
    @SerialName(value = "revision") @Required val revision: kotlin.String,

    /* traQ(サーバー)バージョン */
    @SerialName(value = "version") @Required val version: kotlin.String,

    @SerialName(value = "flags") @Required val flags: VersionFlags

) {


}

