/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 有効なOAuth2トークン情報
 *
 * @param id トークンUUID
 * @param clientId OAuth2クライアントUUID
 * @param scopes スコープ
 * @param issuedAt 発行日時
 */
@Serializable

internal data class ActiveOAuth2Token(

    /* トークンUUID */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* OAuth2クライアントUUID */
    @SerialName(value = "clientId") @Required val clientId: kotlin.String,

    /* スコープ */
    @SerialName(value = "scopes") @Required val scopes: kotlin.collections.List<OAuth2Scope>,

    /* 発行日時 */
    @SerialName(value = "issuedAt") @Required val issuedAt: kotlinx.datetime.Instant

) {


}

