/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * BOTユーザー対
 *
 * @param id BOT UUID
 * @param botUserId BOTユーザーUUID
 */
@Serializable

internal data class BotUser(

    /* BOT UUID */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* BOTユーザーUUID */
    @SerialName(value = "botUserId") @Required val botUserId: kotlin.String

) {


}

