/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * チャンネルパス
 *
 * @param path チャンネルパス
 */
@Serializable

internal data class ChannelPath(

    /* チャンネルパス */
    @SerialName(value = "path") @Required val path: kotlin.String

) {


}

