/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * チャンネル購読レベル 0：無し 1：未読管理 2：未読管理+通知
 *
 * Values: none,subscribed,notified
 */
@Serializable
internal enum class ChannelSubscribeLevel(val value: kotlin.Int) {

    @SerialName(value = "0")
    none(0),

    @SerialName(value = "1")
    subscribed(1),

    @SerialName(value = "2")
    notified(2);

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value.toString()

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is ChannelSubscribeLevel) "$data" else null

        /**
         * Returns a valid [ChannelSubscribeLevel] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): ChannelSubscribeLevel? = data?.let {
            val normalizedData = "$it".lowercase()
            values().firstOrNull { value ->
                it == value || normalizedData == "$value".lowercase()
            }
        }
    }
}

