/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * GET /channelsレスポンス
 *
 * @param `public` パブリックチャンネルの配列
 * @param dm ダイレクトメッセージチャンネルの配列
 */
@Serializable

internal data class ChannelList(

    /* パブリックチャンネルの配列 */
    @SerialName(value = "public") @Required val `public`: kotlin.collections.List<Channel>,

    /* ダイレクトメッセージチャンネルの配列 */
    @SerialName(value = "dm") val dm: kotlin.collections.List<DMChannel>? = null

) {


}

