/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * チャンネル統計情報
 *
 * @param totalMessageCount チャンネルの総投稿メッセージ数(削除されたものも含む)
 * @param stamps チャンネル上のスタンプ統計情報
 * @param users チャンネル上のユーザー統計情報
 * @param datetime 統計情報日時
 */
@Serializable

internal data class ChannelStats(

    /* チャンネルの総投稿メッセージ数(削除されたものも含む) */
    @SerialName(value = "totalMessageCount") @Required val totalMessageCount: kotlin.Long,

    /* チャンネル上のスタンプ統計情報 */
    @SerialName(value = "stamps") @Required val stamps: kotlin.collections.List<ChannelStatsStamp>,

    /* チャンネル上のユーザー統計情報 */
    @SerialName(value = "users") @Required val users: kotlin.collections.List<ChannelStatsUser>,

    /* 統計情報日時 */
    @SerialName(value = "datetime") @Required val datetime: kotlinx.datetime.Instant

) {


}

