/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * チャンネルイベント
 *
 * @param type イベントタイプ
 * @param datetime イベント日時
 * @param detail
 */
@Serializable

internal data class ChannelEvent(

    /* イベントタイプ */
    @SerialName(value = "type") @Required val type: ChannelEvent.Type,

    /* イベント日時 */
    @SerialName(value = "datetime") @Required val datetime: kotlinx.datetime.Instant,

    @SerialName(value = "detail") @Required val detail: ChannelEventDetail

) {

    /**
     * イベントタイプ
     *
     * Values: TopicChanged,SubscribersChanged,PinAdded,PinRemoved,NameChanged,ParentChanged,VisibilityChanged,ForcedNotificationChanged,ChildCreated
     */
    @Serializable
    enum class Type(val value: kotlin.String) {
        @SerialName(value = "TopicChanged")
        TopicChanged("TopicChanged"),
        @SerialName(value = "SubscribersChanged")
        SubscribersChanged("SubscribersChanged"),
        @SerialName(value = "PinAdded")
        PinAdded("PinAdded"),
        @SerialName(value = "PinRemoved")
        PinRemoved("PinRemoved"),
        @SerialName(value = "NameChanged")
        NameChanged("NameChanged"),
        @SerialName(value = "ParentChanged")
        ParentChanged("ParentChanged"),
        @SerialName(value = "VisibilityChanged")
        VisibilityChanged("VisibilityChanged"),
        @SerialName(value = "ForcedNotificationChanged")
        ForcedNotificationChanged("ForcedNotificationChanged"),
        @SerialName(value = "ChildCreated")
        ChildCreated("ChildCreated");
    }

}

