/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 子チャンネル作成イベント
 *
 * @param userId 作成者UUID
 * @param channelId チャンネルUUID
 */
@Serializable

internal data class ChildCreatedEvent(

    /* 作成者UUID */
    @SerialName(value = "userId") @Required val userId: kotlin.String,

    /* チャンネルUUID */
    @SerialName(value = "channelId") @Required val channelId: kotlin.String

) {


}

