/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * クリップフォルダ情報
 *
 * @param id フォルダUUID
 * @param name フォルダ名
 * @param createdAt 作成日時
 * @param ownerId フォルダ所有者UUID
 * @param description 説明
 */
@Serializable

internal data class ClipFolder(

    /* フォルダUUID */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* フォルダ名 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* 作成日時 */
    @SerialName(value = "createdAt") @Required val createdAt: kotlinx.datetime.Instant,

    /* フォルダ所有者UUID */
    @SerialName(value = "ownerId") @Required val ownerId: kotlin.String,

    /* 説明 */
    @SerialName(value = "description") @Required val description: kotlin.String

) {


}

