/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * ダイレクトメッセージチャンネル
 *
 * @param id チャンネルUUID
 * @param userId 送信先相手のUUID
 */
@Serializable

internal data class DMChannel(

    /* チャンネルUUID */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* 送信先相手のUUID */
    @SerialName(value = "userId") @Required val userId: kotlin.String

) {


}

