/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 外部認証アカウントユーザー
 *
 * @param providerName 外部サービス名
 * @param linkedAt 紐付けた日時
 * @param externalName 外部アカウント名
 */
@Serializable

internal data class ExternalProviderUser(

    /* 外部サービス名 */
    @SerialName(value = "providerName") @Required val providerName: kotlin.String,

    /* 紐付けた日時 */
    @SerialName(value = "linkedAt") @Required val linkedAt: kotlin.String,

    /* 外部アカウント名 */
    @SerialName(value = "externalName") @Required val externalName: kotlin.String

) {


}

