/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * サムネイル情報 サムネイルが存在しない場合はnullになります Deprecated: thumbnailsを参照してください
 *
 * @param mime MIMEタイプ
 * @param width サムネイル幅
 * @param height サムネイル高さ
 */
@Serializable
@Deprecated(message = "This schema is deprecated.")

internal data class FileInfoThumbnail(

    /* MIMEタイプ */
    @Deprecated(message = "This property is deprecated.")
    @SerialName(value = "mime") @Required val mime: kotlin.String,

    /* サムネイル幅 */
    @Deprecated(message = "This property is deprecated.")
    @SerialName(value = "width") val width: kotlin.Int? = null,

    /* サムネイル高さ */
    @Deprecated(message = "This property is deprecated.")
    @SerialName(value = "height") val height: kotlin.Int? = null

) {


}

