/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * ファイル情報
 *
 * @param id ファイルUUID
 * @param name ファイル名
 * @param mime MIMEタイプ
 * @param propertySize ファイルサイズ
 * @param md5 MD5ハッシュ
 * @param isAnimatedImage アニメーション画像かどうか
 * @param createdAt アップロード日時
 * @param thumbnails
 * @param thumbnail
 * @param channelId 属しているチャンネルUUID
 * @param uploaderId アップロード者UUID
 */
@Serializable

internal data class FileInfo(

    /* ファイルUUID */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* ファイル名 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* MIMEタイプ */
    @SerialName(value = "mime") @Required val mime: kotlin.String,

    /* ファイルサイズ */
    @SerialName(value = "size") @Required val propertySize: kotlin.Long,

    /* MD5ハッシュ */
    @SerialName(value = "md5") @Required val md5: kotlin.String,

    /* アニメーション画像かどうか */
    @SerialName(value = "isAnimatedImage") @Required val isAnimatedImage: kotlin.Boolean,

    /* アップロード日時 */
    @SerialName(value = "createdAt") @Required val createdAt: kotlinx.datetime.Instant,

    @SerialName(value = "thumbnails") @Required val thumbnails: kotlin.collections.List<ThumbnailInfo>,

    @Deprecated(message = "This property is deprecated.")
    @SerialName(value = "thumbnail") @Required val thumbnail: FileInfoThumbnail?,

    /* 属しているチャンネルUUID */
    @SerialName(value = "channelId") @Required val channelId: kotlin.String?,

    /* アップロード者UUID */
    @SerialName(value = "uploaderId") @Required val uploaderId: kotlin.String?

) {


}

