/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * チャンネル強制通知状態変更イベント
 *
 * @param userId 変更者UUID
 * @param force 変更後強制通知状態
 */
@Serializable

internal data class ForcedNotificationChangedEvent(

    /* 変更者UUID */
    @SerialName(value = "userId") @Required val userId: kotlin.String,

    /* 変更後強制通知状態 */
    @SerialName(value = "force") @Required val force: kotlin.Boolean

) {


}

