/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * メッセージ
 *
 * @param id メッセージUUID
 * @param userId 投稿者UUID
 * @param channelId チャンネルUUID
 * @param content メッセージ本文
 * @param createdAt 投稿日時
 * @param updatedAt 編集日時
 * @param pinned ピン留めされているかどうか
 * @param stamps 押されているスタンプの配列
 * @param threadId スレッドUUID
 */
@Serializable

internal data class Message(

    /* メッセージUUID */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* 投稿者UUID */
    @SerialName(value = "userId") @Required val userId: kotlin.String,

    /* チャンネルUUID */
    @SerialName(value = "channelId") @Required val channelId: kotlin.String,

    /* メッセージ本文 */
    @SerialName(value = "content") @Required val content: kotlin.String,

    /* 投稿日時 */
    @SerialName(value = "createdAt") @Required val createdAt: kotlinx.datetime.Instant,

    /* 編集日時 */
    @SerialName(value = "updatedAt") @Required val updatedAt: kotlinx.datetime.Instant,

    /* ピン留めされているかどうか */
    @SerialName(value = "pinned") @Required val pinned: kotlin.Boolean,

    /* 押されているスタンプの配列 */
    @SerialName(value = "stamps") @Required val stamps: kotlin.collections.List<MessageStamp>,

    /* スレッドUUID */
    @SerialName(value = "threadId") @Required val threadId: kotlin.String?

) {


}

