/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * メッセージに押されたスタンプ
 *
 * @param userId ユーザーUUID
 * @param stampId スタンプUUID
 * @param count スタンプ数
 * @param createdAt スタンプが最初に押された日時
 * @param updatedAt スタンプが最後に押された日時
 */
@Serializable

internal data class MessageStamp(

    /* ユーザーUUID */
    @SerialName(value = "userId") @Required val userId: kotlin.String,

    /* スタンプUUID */
    @SerialName(value = "stampId") @Required val stampId: kotlin.String,

    /* スタンプ数 */
    @SerialName(value = "count") @Required val count: kotlin.Int,

    /* スタンプが最初に押された日時 */
    @SerialName(value = "createdAt") @Required val createdAt: kotlinx.datetime.Instant,

    /* スタンプが最後に押された日時 */
    @SerialName(value = "updatedAt") @Required val updatedAt: kotlinx.datetime.Instant

) {


}

