/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * ピン情報
 *
 * @param userId ピン留めしたユーザーUUID
 * @param pinnedAt ピン留めされた日時
 */
@Serializable

internal data class MessagePin(

    /* ピン留めしたユーザーUUID */
    @SerialName(value = "userId") @Required val userId: kotlin.String,

    /* ピン留めされた日時 */
    @SerialName(value = "pinnedAt") @Required val pinnedAt: kotlinx.datetime.Instant

) {


}

