/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * チャンネル名変更イベント
 *
 * @param userId 変更者UUID
 * @param before 変更前チャンネル名
 * @param after 変更後チャンネル名
 */
@Serializable

internal data class NameChangedEvent(

    /* 変更者UUID */
    @SerialName(value = "userId") @Required val userId: kotlin.String,

    /* 変更前チャンネル名 */
    @SerialName(value = "before") @Required val before: kotlin.String,

    /* 変更後チャンネル名 */
    @SerialName(value = "after") @Required val after: kotlin.String

) {


}

