/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * OAuth2スコープ
 *
 * Values: openid,profile,read,write,manage_bot
 */
@Serializable
internal enum class OAuth2Scope(val value: kotlin.String) {

    @SerialName(value = "openid")
    openid("openid"),

    @SerialName(value = "profile")
    profile("profile"),

    @SerialName(value = "read")
    read("read"),

    @SerialName(value = "write")
    write("write"),

    @SerialName(value = "manage_bot")
    manage_bot("manage_bot");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is OAuth2Scope) "$data" else null

        /**
         * Returns a valid [OAuth2Scope] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): OAuth2Scope? = data?.let {
            val normalizedData = "$it".lowercase()
            values().firstOrNull { value ->
                it == value || normalizedData == "$value".lowercase()
            }
        }
    }
}

