/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * OGPの情報
 *
 * @param type
 * @param title
 * @param url
 * @param images
 * @param description
 * @param videos
 */
@Serializable

internal data class Ogp(

    @SerialName(value = "type") @Required val type: kotlin.String,

    @SerialName(value = "title") @Required val title: kotlin.String,

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "images") @Required val images: kotlin.collections.List<OgpMedia>,

    @SerialName(value = "description") @Required val description: kotlin.String,

    @SerialName(value = "videos") @Required val videos: kotlin.collections.List<OgpMedia>

) {


}

