/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * OGPに含まれる画像の情報
 *
 * @param url
 * @param secureUrl
 * @param type
 * @param width
 * @param height
 */
@Serializable

internal data class OgpMedia(

    @SerialName(value = "url") @Required val url: kotlin.String,

    @SerialName(value = "secureUrl") @Required val secureUrl: kotlin.String?,

    @SerialName(value = "type") @Required val type: kotlin.String?,

    @SerialName(value = "width") @Required val width: kotlin.Int?,

    @SerialName(value = "height") @Required val height: kotlin.Int?

) {


}

