/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * ユーザーグループ編集リクエスト
 *
 * @param name グループ名
 * @param description グループ説明
 * @param type グループタイプ
 */
@Serializable

internal data class PatchUserGroupRequest(

    /* グループ名 */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* グループ説明 */
    @SerialName(value = "description") val description: kotlin.String? = null,

    /* グループタイプ */
    @SerialName(value = "type") val type: kotlin.String? = null

) {


}

