/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * OAuth2クライアント情報変更リクエスト
 *
 * @param name クライアント名
 * @param description 説明
 * @param callbackUrl コールバックURL
 * @param developerId クライアント開発者UUID
 * @param confidential confidential client なら true, public client なら false
 */
@Serializable

internal data class PatchClientRequest(

    /* クライアント名 */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* 説明 */
    @SerialName(value = "description") val description: kotlin.String? = null,

    /* コールバックURL */
    @SerialName(value = "callbackUrl") val callbackUrl: kotlin.String? = null,

    /* クライアント開発者UUID */
    @SerialName(value = "developerId") val developerId: kotlin.String? = null,

    /* confidential client なら true, public client なら false */
    @SerialName(value = "confidential") val confidential: kotlin.Boolean? = null

) {


}

