/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * ユーザーのタグの編集リクエスト
 *
 * @param isLocked タグのロック状態
 */
@Serializable

internal data class PatchUserTagRequest(

    /* タグのロック状態 */
    @SerialName(value = "isLocked") @Required val isLocked: kotlin.Boolean

) {


}

