/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * スタンプ情報変更リクエスト
 *
 * @param name スタンプ名
 * @param creatorId 作成者UUID
 */
@Serializable

internal data class PatchStampRequest(

    /* スタンプ名 */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* 作成者UUID */
    @SerialName(value = "creatorId") val creatorId: kotlin.String? = null

) {


}

