/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Webhook情報変更リクエスト
 *
 * @param name Webhookユーザー表示名
 * @param description 説明
 * @param channelId デフォルトの投稿先チャンネルUUID
 * @param secret Webhookシークレット
 * @param ownerId 移譲先のユーザーUUID
 */
@Serializable

internal data class PatchWebhookRequest(

    /* Webhookユーザー表示名 */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* 説明 */
    @SerialName(value = "description") val description: kotlin.String? = null,

    /* デフォルトの投稿先チャンネルUUID */
    @SerialName(value = "channelId") val channelId: kotlin.String? = null,

    /* Webhookシークレット */
    @SerialName(value = "secret") val secret: kotlin.String? = null,

    /* 移譲先のユーザーUUID */
    @SerialName(value = "ownerId") val ownerId: kotlin.String? = null

) {


}

