/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * チャンネル情報変更リクエスト
 *
 * @param name チャンネル名
 * @param archived アーカイブされているかどうか
 * @param force 強制通知チャンネルかどうか
 * @param parent 親チャンネルUUID
 */
@Serializable

internal data class PatchChannelRequest(

    /* チャンネル名 */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* アーカイブされているかどうか */
    @SerialName(value = "archived") val archived: kotlin.Boolean? = null,

    /* 強制通知チャンネルかどうか */
    @SerialName(value = "force") val force: kotlin.Boolean? = null,

    /* 親チャンネルUUID */
    @SerialName(value = "parent") val parent: kotlin.String? = null

) {


}

