/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * スタンプを押すリクエスト
 *
 * @param count 押す数
 */
@Serializable

internal data class PostMessageStampRequest(

    /* 押す数 */
    @SerialName(value = "count") @Required val count: kotlin.Int

) {


}

