/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * スタンプパレット作成リクエスト
 *
 * @param stamps パレット内のスタンプのUUID配列
 * @param name パレット名
 * @param description 説明
 */
@Serializable

internal data class PostStampPaletteRequest(

    /* パレット内のスタンプのUUID配列 */
    @SerialName(value = "stamps") @Required val stamps: kotlin.collections.Set<kotlin.String>,

    /* パレット名 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* 説明 */
    @SerialName(value = "description") @Required val description: kotlin.String

) {


}

