/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * ユーザータグ追加リクエスト
 *
 * @param tag タグ文字列
 */
@Serializable

internal data class PostUserTagRequest(

    /* タグ文字列 */
    @SerialName(value = "tag") @Required val tag: kotlin.String

) {


}

