/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * BOT作成リクエスト
 *
 * @param name BOTユーザーID 自動的に接頭辞\"BOT_\"が付与されます
 * @param displayName BOTユーザー表示名
 * @param description BOTの説明
 * @param mode
 * @param endpoint BOTサーバーエンドポイント BOT動作モードがHTTPの場合必須です
 */
@Serializable

internal data class PostBotRequest(

    /* BOTユーザーID 自動的に接頭辞\"BOT_\"が付与されます */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* BOTユーザー表示名 */
    @SerialName(value = "displayName") @Required val displayName: kotlin.String,

    /* BOTの説明 */
    @SerialName(value = "description") @Required val description: kotlin.String,

    @SerialName(value = "mode") @Required val mode: BotMode,

    /* BOTサーバーエンドポイント BOT動作モードがHTTPの場合必須です */
    @SerialName(value = "endpoint") val endpoint: kotlin.String? = null

) {


}

