/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Webhook作成リクエスト
 *
 * @param name Webhookユーザーの表示名
 * @param description 説明
 * @param channelId デフォルトの投稿先チャンネルUUID
 * @param secret Webhookシークレット
 */
@Serializable

internal data class PostWebhookRequest(

    /* Webhookユーザーの表示名 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* 説明 */
    @SerialName(value = "description") @Required val description: kotlin.String,

    /* デフォルトの投稿先チャンネルUUID */
    @SerialName(value = "channelId") @Required val channelId: kotlin.String,

    /* Webhookシークレット */
    @SerialName(value = "secret") @Required val secret: kotlin.String

) {


}

