/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * チャンネル作成リクエスト
 *
 * @param name チャンネル名
 * @param parent 親チャンネルのUUID ルートに作成する場合はnullを指定
 */
@Serializable

internal data class PostChannelRequest(

    /* チャンネル名 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* 親チャンネルのUUID ルートに作成する場合はnullを指定 */
    @SerialName(value = "parent") @Required val parent: kotlin.String?

) {


}

