/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 通知をオンにするユーザーのUUID配列
 *
 * @param on 通知をオンにするユーザーのUUID配列
 */
@Serializable

internal data class PutChannelSubscribersRequest(

    /* 通知をオンにするユーザーのUUID配列 */
    @SerialName(value = "on") @Required val on: kotlin.collections.List<kotlin.String>

) {


}

