/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Qallのルーム状態が変更された
 *
 * @param roomStates
 */
@Serializable

internal data class QallRoomStateChangedEvent(

    @SerialName(value = "roomStates") @Required val roomStates: kotlin.collections.List<QallRoomStateChangedEventRoomStatesInner>

) {


}

