/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param metadata ルームに関連付けられたカスタム属性
 */
@Serializable

internal data class QallMetadataRequest(

    /* ルームに関連付けられたカスタム属性 */
    @SerialName(value = "metadata") val metadata: kotlin.String? = null

) {


}

