/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * ルーム内の参加者一覧
 *
 * @param identity ユーザーID_RandomUUID
 * @param name 表示名
 * @param joinedAt 参加した時刻
 * @param attributes ユーザーに関連付けられたカスタム属性
 * @param canPublish 発言権限
 */
@Serializable

internal data class QallParticipant(

    /* ユーザーID_RandomUUID */
    @SerialName(value = "identity") val identity: kotlin.String? = null,

    /* 表示名 */
    @SerialName(value = "name") val name: kotlin.String? = null,

    /* 参加した時刻 */
    @SerialName(value = "joinedAt") val joinedAt: kotlinx.datetime.Instant? = null,

    /* ユーザーに関連付けられたカスタム属性 */
    @SerialName(value = "attributes") val attributes: kotlin.collections.Map<kotlin.String, kotlin.String>? = null,

    /* 発言権限 */
    @SerialName(value = "canPublish") val canPublish: kotlin.Boolean? = null

) {


}

