/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param endpoint LiveKitのエンドポイント
 */
@Serializable

internal data class QallEndpointResponse(

    /* LiveKitのエンドポイント */
    @SerialName(value = "endpoint") @Required val endpoint: kotlin.String

) {


}

