/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param identity ユーザーID_RandomUUID
 * @param name 表示名
 * @param joinedAt 参加した時刻
 * @param canPublish 発言権限
 * @param attributes
 */
@Serializable

internal data class QallRoomStateChangedEventRoomStatesInnerParticipantsInner(

    /* ユーザーID_RandomUUID */
    @SerialName(value = "identity") @Required val identity: kotlin.String,

    /* 表示名 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* 参加した時刻 */
    @SerialName(value = "joinedAt") @Required val joinedAt: kotlinx.datetime.Instant,

    /* 発言権限 */
    @SerialName(value = "canPublish") @Required val canPublish: kotlin.Boolean,

    @SerialName(value = "attributes") val attributes: kotlin.collections.Map<kotlin.String, kotlin.String>? = null

) {


}

