/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param roomId ルームのID
 * @param participants
 * @param isWebinar ウェビナールームかどうか
 * @param metadata ルームに関連付けられたカスタム属性
 */
@Serializable

internal data class QallRoomWithParticipants(

    /* ルームのID */
    @SerialName(value = "roomId") @Required val roomId: kotlin.String,

    @SerialName(value = "participants") @Required val participants: kotlin.collections.List<QallParticipant>,

    /* ウェビナールームかどうか */
    @SerialName(value = "isWebinar") val isWebinar: kotlin.Boolean? = null,

    /* ルームに関連付けられたカスタム属性 */
    @SerialName(value = "metadata") val metadata: kotlin.String? = null

) {


}

