/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param soundId サウンドID (DB登録済み)
 * @param roomName 再生させたいルームのUUID
 */
@Serializable

internal data class SoundboardPlayRequest(

    /* サウンドID (DB登録済み) */
    @SerialName(value = "soundId") @Required val soundId: kotlin.String,

    /* 再生させたいルームのUUID */
    @SerialName(value = "roomName") @Required val roomName: kotlin.String

) {


}

