/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param soundId サーバが発行したサウンドID
 * @param soundName ユーザが指定した表示用のサウンド名
 * @param stampId 任意のスタンプID等、サウンドに紐づく拡張情報
 * @param creatorId 作成者のユーザID
 */
@Serializable

internal data class SoundboardItem(

    /* サーバが発行したサウンドID */
    @SerialName(value = "soundId") @Required val soundId: kotlin.String,

    /* ユーザが指定した表示用のサウンド名 */
    @SerialName(value = "soundName") @Required val soundName: kotlin.String,

    /* 任意のスタンプID等、サウンドに紐づく拡張情報 */
    @SerialName(value = "stampId") @Required val stampId: kotlin.String,

    /* 作成者のユーザID */
    @SerialName(value = "creatorId") @Required val creatorId: kotlin.String

) {


}

