/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param soundId 登録されたサウンドID (ファイル名)
 */
@Serializable

internal data class SoundboardUploadResponse(

    /* 登録されたサウンドID (ファイル名) */
    @SerialName(value = "soundId") @Required val soundId: kotlin.String

) {


}

