/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param ingressId 作成された Ingress のID
 * @param url 作成された Ingress のストリームURL等
 * @param streamKey RTMP配信の場合のstream key
 */
@Serializable

internal data class SoundboardPlayResponse(

    /* 作成された Ingress のID */
    @SerialName(value = "ingressId") @Required val ingressId: kotlin.String,

    /* 作成された Ingress のストリームURL等 */
    @SerialName(value = "url") val url: kotlin.String? = null,

    /* RTMP配信の場合のstream key */
    @SerialName(value = "streamKey") val streamKey: kotlin.String? = null

) {


}

