/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * スタンプ統計情報
 *
 * @param count スタンプ使用総数(同じユーザによって同じメッセージに貼られたものは複数カウントしない)
 * @param totalCount スタンプ使用総数(全てカウント)
 */
@Serializable

internal data class StampStats(

    /* スタンプ使用総数(同じユーザによって同じメッセージに貼られたものは複数カウントしない) */
    @SerialName(value = "count") @Required val count: kotlin.Long,

    /* スタンプ使用総数(全てカウント) */
    @SerialName(value = "totalCount") @Required val totalCount: kotlin.Long

) {


}

