/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * 購読者変更イベント
 *
 * @param userId 変更者UUID
 * @param on オンにされたユーザーのUUID配列
 * @param off オフにされたユーザーのUUID配列
 */
@Serializable

internal data class SubscribersChangedEvent(

    /* 変更者UUID */
    @SerialName(value = "userId") @Required val userId: kotlin.String,

    /* オンにされたユーザーのUUID配列 */
    @SerialName(value = "on") @Required val on: kotlin.collections.List<kotlin.String>,

    /* オフにされたユーザーのUUID配列 */
    @SerialName(value = "off") @Required val off: kotlin.collections.List<kotlin.String>

) {


}

