/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param type
 * @param mime MIMEタイプ
 * @param width サムネイル幅
 * @param height サムネイル高さ
 */
@Serializable

internal data class ThumbnailInfo(

    @SerialName(value = "type") @Required val type: ThumbnailType = ThumbnailType.image,

    /* MIMEタイプ */
    @SerialName(value = "mime") @Required val mime: kotlin.String,

    /* サムネイル幅 */
    @SerialName(value = "width") val width: kotlin.Int? = null,

    /* サムネイル高さ */
    @SerialName(value = "height") val height: kotlin.Int? = null

) {


}

