/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * ユーザーグループ
 *
 * @param id グループUUID
 * @param name グループ名
 * @param description グループ説明
 * @param type グループタイプ
 * @param icon グループアイコンUUID
 * @param members グループメンバーの配列
 * @param createdAt 作成日時
 * @param updatedAt 更新日時
 * @param admins グループ管理者のUUIDの配列
 */
@Serializable

internal data class UserGroup(

    /* グループUUID */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* グループ名 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* グループ説明 */
    @SerialName(value = "description") @Required val description: kotlin.String,

    /* グループタイプ */
    @SerialName(value = "type") @Required val type: kotlin.String,

    /* グループアイコンUUID */
    @SerialName(value = "icon") @Required val icon: kotlin.String,

    /* グループメンバーの配列 */
    @SerialName(value = "members") @Required val members: kotlin.collections.List<UserGroupMember>,

    /* 作成日時 */
    @SerialName(value = "createdAt") @Required val createdAt: kotlinx.datetime.Instant,

    /* 更新日時 */
    @SerialName(value = "updatedAt") @Required val updatedAt: kotlinx.datetime.Instant,

    /* グループ管理者のUUIDの配列 */
    @SerialName(value = "admins") @Required val admins: kotlin.collections.List<kotlin.String>

) {


}

