/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * ユーザー情報
 *
 * @param id ユーザーUUID
 * @param name ユーザー名
 * @param displayName ユーザー表示名
 * @param iconFileId アイコンファイルUUID
 * @param bot BOTかどうか
 * @param state
 * @param updatedAt 更新日時
 */
@Serializable

internal data class User(

    /* ユーザーUUID */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* ユーザー名 */
    @SerialName(value = "name") @Required val name: kotlin.String,

    /* ユーザー表示名 */
    @SerialName(value = "displayName") @Required val displayName: kotlin.String,

    /* アイコンファイルUUID */
    @SerialName(value = "iconFileId") @Required val iconFileId: kotlin.String,

    /* BOTかどうか */
    @SerialName(value = "bot") @Required val bot: kotlin.Boolean,

    @SerialName(value = "state") @Required val state: UserAccountState,

    /* 更新日時 */
    @SerialName(value = "updatedAt") @Required val updatedAt: kotlinx.datetime.Instant

) {


}

