/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param externalLogin 有効な外部ログインプロバイダ
 * @param signUpAllowed ユーザーが自身で新規登録(POST /api/v3/users)可能か
 */
@Serializable

internal data class VersionFlags(

    /* 有効な外部ログインプロバイダ */
    @SerialName(value = "externalLogin") @Required val externalLogin: kotlin.collections.List<kotlin.String>,

    /* ユーザーが自身で新規登録(POST /api/v3/users)可能か */
    @SerialName(value = "signUpAllowed") @Required val signUpAllowed: kotlin.Boolean

) {


}

