/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Webhook情報
 *
 * @param id WebhookUUID
 * @param botUserId WebhookユーザーUUID
 * @param displayName Webhookユーザー表示名
 * @param description 説明
 * @param secure セキュアWebhookかどうか
 * @param channelId デフォルトの投稿先チャンネルUUID
 * @param ownerId オーナーUUID
 * @param createdAt 作成日時
 * @param updatedAt 更新日時
 */
@Serializable

internal data class Webhook(

    /* WebhookUUID */
    @SerialName(value = "id") @Required val id: kotlin.String,

    /* WebhookユーザーUUID */
    @SerialName(value = "botUserId") @Required val botUserId: kotlin.String,

    /* Webhookユーザー表示名 */
    @SerialName(value = "displayName") @Required val displayName: kotlin.String,

    /* 説明 */
    @SerialName(value = "description") @Required val description: kotlin.String,

    /* セキュアWebhookかどうか */
    @SerialName(value = "secure") @Required val secure: kotlin.Boolean,

    /* デフォルトの投稿先チャンネルUUID */
    @SerialName(value = "channelId") @Required val channelId: kotlin.String,

    /* オーナーUUID */
    @SerialName(value = "ownerId") @Required val ownerId: kotlin.String,

    /* 作成日時 */
    @SerialName(value = "createdAt") @Required val createdAt: kotlinx.datetime.Instant,

    /* 更新日時 */
    @SerialName(value = "updatedAt") @Required val updatedAt: kotlinx.datetime.Instant

) {


}

