/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models


import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * skyway用認証リクエストリザルト
 *
 * @param peerId ピアID
 * @param ttl TTL
 * @param timestamp タイムスタンプ
 * @param authToken 認証トークン
 */
@Serializable

internal data class WebRTCAuthenticateResult(

    /* ピアID */
    @SerialName(value = "peerId") @Required val peerId: kotlin.String,

    /* TTL */
    @SerialName(value = "ttl") @Required val ttl: kotlin.Int,

    /* タイムスタンプ */
    @SerialName(value = "timestamp") @Required val timestamp: kotlin.Long,

    /* 認証トークン */
    @SerialName(value = "authToken") @Required val authToken: kotlin.String

) {


}

