/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.github.howard12721.trakt.rest.models

import kotlinx.serialization.Required
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * WebRTC状態
 *
 * @param userId ユーザーUUID
 * @param channelId チャンネルUUID
 * @param sessions セッションの配列
 */
@Serializable

internal data class WebRTCUserState(

    /* ユーザーUUID */
    @SerialName(value = "userId") @Required val userId: kotlin.String,

    /* チャンネルUUID */
    @SerialName(value = "channelId") @Required val channelId: kotlin.String,

    /* セッションの配列 */
    @SerialName(value = "sessions") @Required val sessions: kotlin.collections.List<Session>

) {


}

